version: '3.8'

services:
  pr-cybr-database-agent:
    image: prcybr/pr-cybr-database-agent:latest
    container_name: pr-cybr-database-agent
    env_file: .env # Load environment variables from .env file
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    networks:
      - pr-cybr-net
    ports:
      - "8080:80" # Adjust this port as necessary for the Database Agent

networks:
  pr-cybr-net:
    driver: bridge
