name: Notion Sync

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run the sync in dry-run mode"
        required: false
        default: "true"
        type: choice
        options:
          - "true"
          - "false"
      records_file:
        description: "Path to the JSON file containing records to sync"
        required: false
        default: "config/notion-records.json"
      database_id:
        description: "Notion database ID"
        required: true
      notion_token:
        description: "Notion integration token"
        required: false
        default: ""

permissions:
  contents: read
  issues: read
  pull-requests: read
  discussions: read
  projects: read

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Notion sync
        env:
          NOTION_TOKEN: ${{ inputs.notion_token || secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ inputs.database_id }}
        run: |
          DRY_RUN_FLAG=""
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            DRY_RUN_FLAG="--dry-run"
          fi
          python scripts/notion_sync.py \
            --database-id "$NOTION_DATABASE_ID" \
            --records-file "${{ inputs.records_file }}" \
            $DRY_RUN_FLAG
