name: Run Tests

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [ codex, agents, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v
